### ISSUE TITLE
First time opening Pearcleaner now at the upper right corner

### ISSUE THREAD

**Issue by ghost** [alienator88/Pearcleaner#54] opened 2024-05-03 20:37 UTC

**Comment by alienator88** [comment] 2024-05-03 22:07
Ahhhh, I finally figured out why it's doing that I think.
macOS has its own window size/positioning system that it applies to windows automatically and it was overriding my custom built system sometimes.
I had to set the window.isRestorable to false and that seems to have fixed it on my end. 
This one has been a strange issue that's been around for a while and couldn't figure out why, until now 😂 

Thanks, hopefully this time its fixed for good in the next version I release.

**Comment by 3onion** [comment] 2024-05-04 14:28
> Ahhhh, I finally figured out why it's doing that I think. macOS has its own window size/positioning system that it applies to windows automatically and it was overriding my custom built system sometimes. I had to set the window.isRestorable to false and that seems to have fixed it on my end. This one has been a strange issue that's been around for a while and couldn't figure out why, until now 😂
> 
> Thanks, hopefully this time its fixed for good in the next version I release.

To ensure that a macOS app developed in Swift starts centered on the screen, you can set the window position in your application's code. This is typically done in the `AppDelegate` or directly within the window setup code if you are not using Storyboards. Here’s how you can do it using Swift:

### Step-by-Step Guide:

1. **Create the Window**: If you are setting up your window programmatically, ensure you have a reference to your window. If you are using Storyboards, you might already have this set up.

2. **Center the Window**: You can center the window by modifying the window's `frame` property based on the screen's dimensions. Here’s a simple way to adjust the window position to be centered on the screen:

    ```swift
    import Cocoa

    class AppDelegate: NSObject, NSApplicationDelegate {
        var window: NSWindow?

        func applicationDidFinishLaunching(_ aNotification: Notification) {
            let screenSize = NSScreen.main?.frame.size ?? CGSize(width: 800, height: 600)
            let windowSize = CGSize(width: 600, height: 400)  // Set your desired window size here

            let originX = (screenSize.width - windowSize.width) / 2
            let originY = (screenSize.height - windowSize.height) / 2
            let windowFrame = CGRect(x: originX, y: originY, width: windowSize.width, height: windowSize.height)

            // Initialize the window with the computed frame
            window = NSWindow(contentRect: windowFrame,
                              styleMask: [.titled, .closable, .miniaturizable, .resizable],
                              backing: .buffered,
                              defer: false)
            window?.center()
            window?.makeKeyAndOrderFront(nil)
        }
    }
    ```

    In this example:
    - I calculate the `originX` and `originY` to position the window in the center of the screen.
    - The `windowSize` is the desired size of your window.
    - We then set the `window`’s frame to these calculated values and make it key and front, effectively centering it.

3. **Launch Configuration**: Ensure that your AppDelegate is set correctly in your `main.swift` or is linked properly in your Storyboard setup.

This approach ensures that your app window will start centered on the screen, regardless of the screen resolution or changes in display configurations. If your app supports multiple windows, you'll need to manage the positioning for each window similarly.

**Comment by alienator88** [comment] 2024-05-04 14:48
That is straight up ChatGPT, how is this helpful? 😂 That doesn't even apply here though.
 
First of all, that code would open the app window center screen every single time the app is launched, not just the first launch ever. Which I don't want to force onto users. They should be able to position an app window anywhere and have it remember that position.

Second, I already have code implemented for opening the app middle screen on first launch, it's just being buggy because of what I mentioned previously, which I believe I have fixed now, as mentioned already. See here: https://github.com/alienator88/Pearcleaner/blob/2dc3bee97315bbe7c666cbbb5b81b3f13ea945a7/Pearcleaner/Windows/WindowSettings.swift

And third, that code is for AppKit, this is mainly a SwiftUI app and launches the window via a WindowGroup on startup, not appdelegate.

**Comment by 3onion** [comment] 2024-05-04 14:52
> That is straight up ChatGPT, how is this helpful? 😂 That doesn't even apply here though.
> 
> First of all, that code would open the app window center screen every single time the app is launched, not just the first launch ever. Which I don't want to force onto users. They should be able to position an app window anywhere and have it remember that position.
> 
> Second, I already have code implemented for opening the app middle screen on first launch, it's just being buggy because of what I mentioned previously, which I believe I have fixed now, as mentioned already. See here: https://github.com/alienator88/Pearcleaner/blob/2dc3bee97315bbe7c666cbbb5b81b3f13ea945a7/Pearcleaner/Windows/WindowSettings.swift
> 
> And third, that code is for AppKit, this is mainly a SwiftUI app and launches the window via a WindowGroup on startup, not appdelegate.

You are right, I copy that from ChatGPT. I code more on Python. Never coded in Swift. I just posted it because I thought that it could help. If don’t help, at least I tried.

**Comment by alienator88** [comment] 2024-05-04 14:58
It's all good, just didn't see where that fit in with the current issue. I guess it's more related to macOS and how it handles window positioning inherently, which I forgot to disable in my window system before.

Before I push out a release, can I give you a zip file of a debug version to test on your end if the issue is resolved?

**Comment by 3onion** [comment] 2024-05-04 15:00
> It's all good, just didn't see where that fit in with the current issue. I guess it's more related to macOS and how it handles window positioning inherently, which I forgot to disable in my window system before.
> 
> Before I push out a release, can I give you a zip file of a debug version to test on your end if the issue is resolved?

Yes, sure.

**Comment by alienator88** [comment] 2024-05-04 15:01
Cool, it will be today sometime or tomorrow if I don't have time today.

**Comment by alienator88** [comment] 2024-05-05 23:05
Okay, go ahead and try this one and let me know if it opens correctly the first time.
Please note that if you have opened Pearcleaner on the computer you are testing this on before, it will have saved coordinates for position already in user defaults. You can clear those out with this command in Terminal before opening it: `defaults delete com.alienator88.Pearcleaner windowYKey; defaults delete com.alienator88.Pearcleaner windowXKey`

This will delete the X and Y coordinate for the window positioning if it has saved them before.

[Pearcleaner.zip](https://github.com/alienator88/Pearcleaner/files/15214857/Pearcleaner.zip)

**Comment by 3onion** [comment] 2024-05-05 23:19
> Okay, go ahead and try this one and let me know if it opens correctly the first time. Please note that if you have opened Pearcleaner on the computer you are testing this on before, it will have saved coordinates for position already in user defaults. You can clear those out with this command in Terminal before opening it: `defaults delete com.alienator88.Pearcleaner windowYKey; defaults delete com.alienator88.Pearcleaner windowXKey`
> 
> This will delete the X and Y coordinate for the window positioning if it has saved them before.
> 
> [Pearcleaner.zip](https://github.com/alienator88/Pearcleaner/files/15214857/Pearcleaner.zip)

Pearcleaner now appears centered on the screen. The problem appears to be solved.
Just one question. Why when we select the option to uninstall Pearcleaner it doesn't also delete the "com.alienator88.Pearcleaner" folder?

**Comment by alienator88** [comment] 2024-05-05 23:21
Great to hear!

Let me check, the application support folders used to be named Pearcleaner. I might have forgotten to check for the new folder name using the bundle id. I'll get back to you in a sec.

**Comment by alienator88** [comment] 2024-05-05 23:27
I just tested on my end and it cleaned everything out. What folder in what path is it not removing for you?

**Comment by 3onion** [comment] 2024-05-05 23:32
> I just tested on my end and it cleaned everything out. What folder in what path is it not removing for you?

Now the problem has reappeared. The location of the "delete com.alienator88.Pearcleaner" folder is ~/Library/Application\ Scripts/com.alienator88.Pearcleaner.FinderOpen

**Comment by alienator88** [comment] 2024-05-05 23:34
What do you mean reappeared? Which problem, the centering issue or this remaining folder left behind?

**Comment by 3onion** [comment] 2024-05-05 23:36
> What do you mean reappeared? Which problem, the centering issue or this remaining folder left behind?

When starting the first time the window appeared in the upper right corner. Let me do one more test, please.

**Comment by alienator88** [comment] 2024-05-05 23:41
I found the issue with the remaining folder on uninstall. There was a race condition happening and it was attempting to delete the folders before all of them were done being added to the deletion list. I'll have a fix for this in next version.

**Comment by 3onion** [comment] 2024-05-05 23:42
Here is the state of the app:

1- When starting the application for the first time, it continues to appear in the upper right corner, even when deleting the `com.alienator88.Pearcleaner` folder located in `~Library/Application\ Scripts/com.alienator88.Pearcleaner`

2- When selecting the Uninstall Pearcleaner option, the `com.alienator88.Pearcleaner` folder located in `~Library/Application\ Scripts/com.alienator88.Pearcleaner` does not delete.

**Comment by 3onion** [comment] 2024-05-05 23:49
> I found the issue with the remaining folder on uninstall. There was a race condition happening and it was attempting to delete the folders before all of them were done being added to the deletion list. I'll have a fix for this in next version.

Even with `com.alienator88.Pearcleaner` folder deleted from `~/Library/Application\ Scripts/com.alienator88.Pearcleaner` the app continues to appear in the upper right corner of the screen.

**Comment by alienator88** [comment] 2024-05-06 00:09
Run this command in terminal one more time: 
`defaults delete com.alienator88.Pearcleaner windowYKey; defaults delete com.alienator88.Pearcleaner windowXKey`

And try this version:
[Pearcleaner.zip](https://github.com/alienator88/Pearcleaner/files/15214998/Pearcleaner.zip)


If this doesn't work still, I'm not sure what to tell you. I just tested this on multiple macs I have and it behaved as it was coded:
1. First launch ever opens center screen
2. Subsequent launches open wherever the user left the window the previous time

Also, the Uninstall issue is fixed in this version as well.

**Comment by alienator88** [comment] 2024-05-06 00:10
I've also tested this with external monitors and just laptop screen alone, they all behaved the same on my end.

**Comment by 3onion** [comment] 2024-05-06 00:18
> Run this command in terminal one more time: `defaults delete com.alienator88.Pearcleaner windowYKey; defaults delete com.alienator88.Pearcleaner windowXKey`
> 
> And try this version: [Pearcleaner.zip](https://github.com/alienator88/Pearcleaner/files/15214998/Pearcleaner.zip)
> 
> If this doesn't work still, I'm not sure what to tell you. I just tested this on multiple macs I have and it behaved as it was coded:
> 
> 1. First launch ever opens center screen
> 2. Subsequent launches open wherever the user left the window the previous time
> 
> Also, the Uninstall issue is fixed in this version as well.

Here are the results of my test:
1- When opening the first time, the window still appears in the upper right corner (with the `com.alienator88.Pearcleaner` folder located at `~/Library/Application\ Scripts/com.alienator88.Pearcleaner` deleted)
2- When opening the Pearcleaner app for the second time, the app appears centered on the screen.
3- When selecting the Uninstall Pearcleaner option, it still does not delete the `com.alienator88.Pearcleaner` folder located at `~/Library/Application\ Scripts/com.alienator88.Pearcleaner`

**Comment by alienator88** [comment] 2024-05-06 00:27
Can you shoot me a screen recording?

**Comment by 3onion** [comment] 2024-05-06 00:29
> Can you shoot me a screen recording?

Sure, one second.

**Comment by 3onion** [comment] 2024-05-06 00:34
> Can you shoot me a screen recording?

Tells me that the video is too big!

**Comment by alienator88** [comment] 2024-05-06 01:28
Oh yeah, Github has a file size limit. How big is it? Can you upload it to a video hosting site and link it?
Also, are you able to reproduce the issue on more than one computer? As mentioned before, I tested this on a few different ones and can't seem to get the problem you are.

**Comment by 3onion** [comment] 2024-05-06 02:35
After several tests I found that:
1- Pearcleaner always starts in the upper right corner when opening in the first time with or not `com.alienator88.Pearcleaner` located at `~/Library/Application\ Scripts/com.alienator88.Pearcleaner` 
2- When selecting the `Uninstall Pearcleaner` option in the menu, it still does not delete the `com.alienator88.Pearcleaner` folder located at `~/Library/Application\ Scripts/com.alienator88.Pearcleaner`
3- Uninstalling Pearcleaner with AppCleaner `com.alienator88.Pearcleaner` folder located at `~/Library/Application\ Scripts/com.alienator88.Pearcleaner` is **deleted**.

**Comment by alienator88** [comment] 2024-05-06 02:45
I don't know what to tell you at this point. I'm just unable to reproduce these two issues on my end on multiple computers and a virtual machine. The behavior I'm seeing is:
1. App opens center screen first time and then it opens wherever you left it last on follow-up openings, as it should. 
2. The uninstall is finding all of the app files and removing them.

Are you seeing this on more than one computer? Wonder if there's something environmentally different on yours than mine.

**Comment by 3onion** [comment] 2024-05-06 03:01
> I don't know what to tell you at this point. I'm just unable to reproduce these two issues on my end on multiple computers and a virtual machine. The behavior I'm seeing is:
> 
> 1. App opens center screen first time and then it opens wherever you left it last on follow-up openings, as it should.
> 2. The uninstall is finding all of the app files and removing them.
> 
> Are you seeing this on more than one computer? Wonder if there's something environmentally different on yours than mine.

Try this for my please. Change `loadWindowSettings()` function to this:

`func loadWindowSettings() -> NSRect {
    // Retrieve window size from UserDefaults or use default values
    let defaultWidth = 800.0 // Default width when not set
    let defaultHeight = 600.0 // Default height when not set
    let width = CGFloat(UserDefaults.standard.float(forKey: mini ? windowWidthKeyMini : windowWidthKey)) == 0 ? defaultWidth : CGFloat(UserDefaults.standard.float(forKey: mini ? windowWidthKeyMini : windowWidthKey))
    let height = CGFloat(UserDefaults.standard.float(forKey: mini ? windowHeightKeyMini : windowHeightKey)) == 0 ? defaultHeight : CGFloat(UserDefaults.standard.float(forKey: mini ? windowHeightKeyMini : windowHeightKey))

    // Try to get the screen size from the main display
    let screenFrame = NSScreen.main?.visibleFrame ?? NSRect(x: 0, y: 0, width: defaultWidth, height: defaultHeight)

    // Calculate default position to center the window on the screen
    var x = CGFloat(UserDefaults.standard.float(forKey: windowXKey))
    var y = CGFloat(UserDefaults.standard.float(forKey: windowYKey))

    // Check if x and y are set in UserDefaults; if not, center the window
    if UserDefaults.standard.object(forKey: windowXKey) == nil || UserDefaults.standard.object(forKey: windowYKey) == nil {
        x = (screenFrame.width - width) / 2 + screenFrame.origin.x
        y = (screenFrame.height - height) / 2 + screenFrame.origin.y
    }

    // Return the new frame
    return NSRect(x: x, y: y, width: width, height: height)
}
`

I think the problem is in `UserDefaults`.

**Comment by alienator88** [comment] 2024-05-06 03:15
Sorry, not at computer right now. What is it that was added/changed? Default window sizing?

**Comment by 3onion** [comment] 2024-05-06 03:22
> Sorry, not at computer right now. What is it that was added/changed? Default window sizing?

 The function is in `loadWindowSettings() ` `WindowSettings.swift`. The idea is to ensure that the default window position is calculated accurately.

This function add default dimensions for width and height to ensure that if UserDefaults returns zero (indicative of not being set), the window will use sensible default dimensions. This helps in cases where UserDefaults might not yet have any stored values.

Due to this issue I started to study Swift with the help of some books and with the help of a mix of ChatGPT and Gemini. 😂

**Comment by alienator88** [comment] 2024-05-06 03:35
I'll test it out tomorrow. I didn't think of the window sizing causing the bug because the views used to have a default size already set, but not anymore. When I load the window settings from user defaults it overwrites those sizes with nil probably and causes the problem maybe.

I'll let you know what happens, thanks for the assist :)

**Comment by alienator88** [comment] 2024-05-06 16:34
I think you might have been onto something here. When I was doing my testing before, I was only clearing out the x/y position and not the sizes I already had saved. When I cleared the x/y position and window size, I did have the app launch in a strange spot first time, not centered on the screen.

I added a new function in the WindowSettings class for registering default values for size and position if they don't exist:
``` swift
func registerDefaultWindowSettings(completion: @escaping () -> Void = {}) {

        let defaults = UserDefaults.standard

        // Get primary screen
        let screenFrame = NSScreen.main?.visibleFrame ?? NSRect(x: 0, y: 0, width: 800, height: 600)

        // Calculate default window sizes and x/y coordinates
        let defaultWidth = Float(900)  // Default width for regular window
        let defaultHeight = Float(600) // Default height for regular window
        let defaultWidthMini = Float(300) // Default width for mini window
        let defaultHeightMini = Float(370)  // Default height for mini window
        let defaultX = Float((screenFrame.width - CGFloat(defaultWidth)) / 2 + screenFrame.origin.x) // Default X coordinate
        let defaultY = Float((screenFrame.height - CGFloat(defaultHeight)) / 2 + screenFrame.origin.y) // Default Y coordinate

        // Set defaults only if they are not already set
        if defaults.object(forKey: windowWidthKey) == nil {
            defaults.set(defaultWidth, forKey: windowWidthKey)
        }
        if defaults.object(forKey: windowHeightKey) == nil {
            defaults.set(defaultHeight, forKey: windowHeightKey)
        }
        if defaults.object(forKey: windowWidthKeyMini) == nil {
            defaults.set(defaultWidthMini, forKey: windowWidthKeyMini)
        }
        if defaults.object(forKey: windowHeightKeyMini) == nil {
            defaults.set(defaultHeightMini, forKey: windowHeightKeyMini)
        }
        if defaults.object(forKey: windowXKey) == nil {
            defaults.set(defaultX, forKey: windowXKey)
        }
        if defaults.object(forKey: windowYKey) == nil {
            defaults.set(defaultY, forKey: windowYKey)
        }
        completion()
    }
```

I run this once on application load to do the check. Tested it on a couple computers and it seems to work okay. 
Can you run this one on your side as well and see what you get?
[Pearcleaner.zip](https://github.com/alienator88/Pearcleaner/files/15223635/Pearcleaner.zip)

**Comment by 3onion** [comment] 2024-05-06 16:58
> I think you might have been onto something here. When I was doing my testing before, I was only clearing out the x/y position and not the sizes I already had saved. When I cleared the x/y position and window size, I did have the app launch in a strange spot first time, not centered on the screen.
> 
> I added a new function in the WindowSettings class for registering default values for size and position if they don't exist:
> 
> ```swift
> func registerDefaultWindowSettings(completion: @escaping () -> Void = {}) {
> 
>         let defaults = UserDefaults.standard
> 
>         // Get primary screen
>         let screenFrame = NSScreen.main?.visibleFrame ?? NSRect(x: 0, y: 0, width: 800, height: 600)
> 
>         // Calculate default window sizes and x/y coordinates
>         let defaultWidth = Float(900)  // Default width for regular window
>         let defaultHeight = Float(600) // Default height for regular window
>         let defaultWidthMini = Float(300) // Default width for mini window
>         let defaultHeightMini = Float(370)  // Default height for mini window
>         let defaultX = Float((screenFrame.width - CGFloat(defaultWidth)) / 2 + screenFrame.origin.x) // Default X coordinate
>         let defaultY = Float((screenFrame.height - CGFloat(defaultHeight)) / 2 + screenFrame.origin.y) // Default Y coordinate
> 
>         // Set defaults only if they are not already set
>         if defaults.object(forKey: windowWidthKey) == nil {
>             defaults.set(defaultWidth, forKey: windowWidthKey)
>         }
>         if defaults.object(forKey: windowHeightKey) == nil {
>             defaults.set(defaultHeight, forKey: windowHeightKey)
>         }
>         if defaults.object(forKey: windowWidthKeyMini) == nil {
>             defaults.set(defaultWidthMini, forKey: windowWidthKeyMini)
>         }
>         if defaults.object(forKey: windowHeightKeyMini) == nil {
>             defaults.set(defaultHeightMini, forKey: windowHeightKeyMini)
>         }
>         if defaults.object(forKey: windowXKey) == nil {
>             defaults.set(defaultX, forKey: windowXKey)
>         }
>         if defaults.object(forKey: windowYKey) == nil {
>             defaults.set(defaultY, forKey: windowYKey)
>         }
>         completion()
>     }
> ```
> 
> I run this once on application load to do the check. Tested it on a couple computers and it seems to work okay. Can you run this one on your side as well and see what you get? [Pearcleaner.zip](https://github.com/alienator88/Pearcleaner/files/15223635/Pearcleaner.zip)

Sure, one second.

**Comment by alienator88** [comment] 2024-05-06 17:04
I haven't done anything else to the uninstall related function, so might not see anything different there

**Comment by 3onion** [comment] 2024-05-06 17:07
> I haven't done anything else to the uninstall related function, so might not see anything different there

Now it has opened for the first time right in the center of the screen.

Uninstallation now only works after the third time. It appears twice to confirm uninstallation, but does not uninstall. The third time it uninstalled. Please watch the video..


https://github.com/alienator88/Pearcleaner/assets/168279042/dc482168-8ab2-4e37-8687-1eb3f8ed2ffd

**Comment by 3onion** [comment] 2024-05-06 17:11
I forgot to say that upon uninstallation a crash reporter plist file is created.

**Comment by alienator88** [comment] 2024-05-06 17:13
I'll look into it, the reason for the crash reporter is most likely because I have to Terminate the app itself during the process. 
It's very difficult to terminate an app and have it perform uninstall actions at the same time because if it hits a race condition it might end before it is done finding files and deleting them. Having a hard time finding a middle ground. But I'll keep working on it.

**Comment by 3onion** [comment] 2024-05-06 17:16
> I'll look into it, the reason for the crash reporter is most likely because I have to Terminate the app itself during the process. It's very difficult to terminate an app and have it perform uninstall actions at the same time because if it hits a race condition it might end before it is done finding files and deleting them. Having a hard time finding a middle ground. But I'll keep working on it.

Also see the part about deleting orphans. Because I tested it and deleted a lot of files related to other applications, such as the Get Backup Pro application.

**Comment by alienator88** [comment] 2024-05-06 17:21
If you're referring to the leftover file search, see the message displayed in the app:
![image](https://github.com/alienator88/Pearcleaner/assets/6263626/f3a49da9-09fa-4e53-a6b6-e4b9321ce1f2)

This search WILL find unrelated files because without application bundles available from old apps that were removed, I have no way of knowing the files to avoid. This is a best guess scenario. 

The user has to go through the list and check the items that are related to old apps they might've had. Pearcleaner has no way of knowing that information after the apps have already been deleted unfortunately.

**Comment by 3onion** [comment] 2024-05-06 17:55
> This search WILL find unrelated files because without application bundles available from old apps that were removed, I have no way of knowing the files to avoid. This is a best guess scenario.
> 
> The user has to go through the list and check the items that are related to old apps they might've had. Pearcleaner has no way of knowing that information after the apps have already been deleted unfortunately.

AppDelete had that function and worked pretty well.
What do you think of this idea:
You can track application installation and usage by monitoring installations, for example, by monitoring system logs or using macOS APIs to detect changes in the /Applications directory. 

To detect orphans files you can maintain a database or a registry file that logs all files and directories created by applications. This registry should be updated whenever an application is used, creating, modifying, or deleting files.

After an application is deleted, the registry for any files and directories associated with it should be checked.

To identify orphans, once an app is removed, mark all associated files in your registry as potential orphans.

Other apps use this approach like UninstallPKG. I made my own zsh shell script to uninstall PKG files. You can see it in this zip files:

[Uploading uninstall_pkg_with_list.sh.zip…]()

**Comment by alienator88** [comment] 2024-05-06 18:26
The attachment didn't get uploaded correctly if you wanna try again.
Also, not sure I want to go that deep with that feature. I honestly didn't even want to add the initial implementation even. 
My goal for this app was to do one thing and do that good, which was find app files and remove them.
The leftover file search wasn't really something I was interested in but added it from a feature request.

The issue I see with your registry example is that I couldn't apply that to old applications that have already been deleted in the past before Pearcleaner was installed, so it would only work for current/future apps. And also it would require my app to run in the background and constantly monitor file system changes for these apps. Just not sure I want to add all that overhead.

**Comment by 3onion** [comment] 2024-05-06 18:47
> The attachment didn't get uploaded correctly if you wanna try again. 
>
Try to download now in the other comment

>Also, not sure I want to go that deep with that feature. I honestly didn't even want to add the initial implementation even. My goal for this app was to do one thing and do that good, which was find app files and remove them. The leftover file search wasn't really something I was interested in but added it from a feature request.
> 

I understand.

> The issue I see with your registry example is that I couldn't apply that to old applications that have already been deleted in the past before Pearcleaner was installed, so it would only work for current/future apps. And also it would require my app to run in the background and constantly monitor file system changes for these apps. Just not sure I want to add all that overhead.
>

I agree with you, the problem would be orphaned files from applications uninstalled before installing Pearcleaner. And yes, it require that your app run in the background and constantly monitor file system changes for those apps.

**Comment by alienator88** [comment] 2024-05-06 20:23
Agreed, at least for now. This app is only months old really, so want to get it super stable with the main function before going that route.

**Comment by 3onion** [comment] 2024-05-08 14:06
Pearcleaner Uninstall menu do not work well in 3.6.1 and in 3.6.2.

**Comment by alienator88** [comment] 2024-05-08 16:16
So this is the behavior I see on my end when I test on both of my physical computers:

https://github.com/alienator88/Pearcleaner/assets/6263626/5eee8724-aeeb-48bf-844f-0536618a8c6f

And this is the behavior I see even in my macOS virtual machine (it's a bit slow 😂 ):

https://github.com/alienator88/Pearcleaner/assets/6263626/fcc78d93-14de-40b0-a164-52e3e574e490


I really don't get why you see the alert come up twice like that, it's just a basic alert popup:
``` swift
.alert(isPresented: $appState.showUninstallAlert) {
                Alert(
                    title: Text("Warning!"),
                    message: Text("Pearcleaner and all of its files will be cleanly removed, are you sure?"),
                    primaryButton: .destructive(Text("Uninstall")) {
                        uninstallPearcleaner(appState: appState, locations: locations)
                    },
                    secondaryButton: .cancel()
                )
            }
```

**Comment by 3onion** [comment] 2024-05-08 17:59
I have been analyzing the file code `FinderOpen.swift`. And I came to the following conclusion:
Ensure that FinderOpen is instantiated as a singleton if that's not currently enforced and check the conditions under which the menu items are added. Make sure that the menu is cleared or properly refreshed before adding new items to prevent duplication.

**Comment by alienator88** [comment] 2024-05-08 18:05
FinderOpen is the Finder extension that adds the "Pearcleaner Uninstall" option to the context menu when you right click an app in Finder. As far as I know and have tested, the Finder extension works fine.
![image](https://github.com/alienator88/Pearcleaner/assets/6263626/44f5787f-6e93-46a7-bc61-f18e53c28a92)

I'm not understanding the correlation between that and the actual uninstaller function for the Pearcleaner app itself.
![image](https://github.com/alienator88/Pearcleaner/assets/6263626/d1f29282-4593-4224-bce4-a9b57d4f7845)

They are two different functions. Can you explain why you believe that is related to the alert popup issue?

**Comment by 3onion** [comment] 2024-05-08 18:15
Just to make one test. Tell me all files related to the uninstallation and the graphical (SwiftUI) code of the button to accept the uninstallation.

**Comment by alienator88** [comment] 2024-05-08 18:29
I'm sorry man, but I don't have time to pick through the code for you and explain how it all works together. 
Download the repo, run the app in xcode and see which functions it calls.
If you find anything interesting that stands out, let me know :) I gotta get back to my day job 😂

**Comment by 3onion** [comment] 2024-05-08 18:30
> I'm sorry man, but I don't have time to pick through the code for you and explain how it all works together. Download the repo, run the app in xcode and see which functions it calls. If you find anything interesting that stands out, let me know :) I gotta get back to my day job 😂

I also have a job. I was trying to help you. Have a nice day.

**Comment by alienator88** [comment] 2024-05-08 18:32
That's fine, you can help if you want. But I don't have time to explain everything.
Just gotta look through the code and play around.

**Comment by alienator88** [comment] 2024-05-13 16:55
Closing this specific issue as the problem in the issue title should now be resolved.

**Closed by alienator88** 2024-05-13 16:55 UTC
