### ISSUE TITLE
[BUG] Finder Handler Errors

### ISSUE THREAD

**Issue by L1cardo** [alienator88/Pearcleaner#172] opened 2024-11-29 02:31 UTC
### Describe the bug:
Pearcleaner won't uninstall app sometimes, it only appears  sometimes, not everytime	, so you may be not able to reproduce.

### Steps to reproduce:
Try to uninstall app from finder extension 

### Info:
 - OS: [macOS 15.1.1]
 - Pearcleaner Version: [4.0.2]

### Screenshots:
https://github.com/user-attachments/assets/e4e70b37-1817-45a6-8b7d-023cc20895ed

### Console Logs (For app crashes or hard to reproduce issues):
 1. Open the Terminal app and run the following command
```
log stream --level debug --style compact --predicate 'subsystem == "com.alienator88.Pearcleaner"'
```
![image](https://github.com/user-attachments/assets/9c397936-87a2-446d-85d0-85cef105215e)

**Comment by alienator88** [comment] 2024-12-02 17:40
Hmm, yeah I haven't seen this issue before. I tried testing a few times with that same app you have in the video and I haven't been able to reproduce so far.
I'm curious if it's related to one of the files it attempts to delete. That AppleScript error is really weird..

**Comment by pantheraleo-7** [comment] 2024-12-03 19:06
Speaking of uninstallation: I wanted to ask whether pearcleaner '[zaps](https://docs.brew.sh/Cask-Cookbook#stanza-zap)' the homebrew installed cask or not?

**Comment by alienator88** [comment] 2024-12-03 19:11
I think currently it only has `uninstall --force` set for the cask cleanup command. 
I can add the --zap in there too just in case, but usually those folders are already caught by my app. Wouldn't hurt to add it though, good idea.

**Comment by pantheraleo-7** [comment] 2024-12-03 19:17
> usually those folders are already caught by my app

Not always I guess. I tried pearcleaner for the first time with `raspberry-pi-imager` (installed via homebrew) and it left `~/Library/Caches/Raspberry Pi`.

**Comment by alienator88** [comment] 2024-12-03 20:15
That's likely because the app name "Raspberry Pi Imager" and the folder is called "Raspberry Pi". Currently it only matches on app name and partial bundle identifiers.
Without changing the name search algorithm, it wouldn't catch that currently.
I did add fuzzy app name searching in the app list filtering, I might be able to use that to do fuzzy app name searches for the files as well.
I'll look into it.

**Comment by L1cardo** [comment] 2024-12-03 23:20
That unicode translates into 
```bash
NSAppleScriptErrorBriefMessage = "处理程序不能处理这个类的对象。";
NSAppleScriptErrorMessage = "“Finder”遇到一个错误：处理程序不能处理这个类的对象。";
```

Which is 
```
NSAppleScriptErrorBriefMessage = "The handler cannot handle this type of object.";
NSAppleScriptErrorMessage = "Finder encountered an error: The handler cannot handle this type of object.";
```

**Comment by alienator88** [comment] 2024-12-03 23:32
Right, which is why I was wondering if it's related to one of the files it was trying to delete.
You can hit CMD+E when looking at the files view to export a list of all the files into a text document.
Might help getting a list of those files.

The thing is there are a few things that can cause that handler error, file types, invalid paths, locked files, permissions, etc.
Unfortunately without being able to repro on my end, it's really a guess in the dark for me.
If you do repro again, export that list of file paths and maybe try deleting each file, one at a time and see which one causes the error. You could do it using Script Editor with something like:
```
set posixPath to "/path/to/your/file.txt"
tell application "Finder"
    delete (POSIX file posixPath)
end tell
```

**Comment by alienator88** [comment] 2024-12-03 23:40
Something that I `think` could be a cause is maybe one of the files it finds in the Cache or Temp directories. 
If they move or get deleted right before hitting Uninstall, it would actually crash the whole applescript for deleting all the files. I can probably add a check to make sure each file still exists right before running the script, if that was the issue here.

**Comment by L1cardo** [comment] 2024-12-03 23:44
I can't reproduce either, it just happens sometimes, but I will pay more attention when it happens next time

**Comment by alienator88** [comment] 2024-12-03 23:45
Sounds good!
Meanwhile, I'll add a validation function to the trash function to check each file path before passing it to the applescript.

**Comment by L1cardo** [comment] 2024-12-04 08:49
> Right, which is why I was wondering if it's related to one of the files it was trying to delete. You can hit CMD+E when looking at the files view to export a list of all the files into a text document. Might help getting a list of those files.
> 
> The thing is there are a few things that can cause that handler error, file types, invalid paths, locked files, permissions, etc. Unfortunately without being able to repro on my end, it's really a guess in the dark for me. If you do repro again, export that list of file paths and maybe try deleting each file, one at a time and see which one causes the error. You could do it using Script Editor with something like:
> 
> ```
> set posixPath to "/path/to/your/file.txt"
> tell application "Finder"
>     delete (POSIX file posixPath)
> end tell
> ```

This AppleScript has problem, it say can't find POSIX
![image](https://github.com/user-attachments/assets/b4fd10b1-0f90-4594-9316-6ff75584b5cc)

**Comment by alienator88** [comment] 2024-12-04 16:12
Can probably simplify that apple script to this:
```
tell application "Finder"
	delete POSIX file "/Users/licardo/Downloads/1.txt"
end tell
```

**Comment by L1cardo** [comment] 2024-12-06 16:03
There is this file, but the script can't delete it.
![image](https://github.com/user-attachments/assets/3a2e8205-aa55-4428-ab41-81a7f5afa7d8)

This is the whole file path
```bash
/Applications/Proxyman.app
/Library/LaunchDaemons/com.proxyman.NSProxy.HelperTool.plist
/Library/PrivilegedHelperTools/com.proxyman.NSProxy.HelperTool
~/.proxyman
~/.proxyman-data
~/Library/Application Support/com.proxyman.NSProxy
~/Library/Caches/Proxyman
~/Library/Caches/com.proxyman.NSProxy
~/Library/HTTPStorages/com.proxyman.NSProxy
~/Library/Preferences/com.proxyman.NSProxy.plist
~/Library/Preferences/com.proxyman.iconappmanager.userdefaults.plist
~/Library/Saved Application State/com.proxyman.NSProxy.savedState
~/Library/WebKit/com.proxyman.NSProxy
/var/folders/my/yxdm17rn3rx1xccnxlyj4_5m0000gn/C/com.proxyman.NSProxy
/var/folders/my/yxdm17rn3rx1xccnxlyj4_5m0000gn/T/com.proxyman.NSProxy
```

Above those files, the script failed to deletes files start with `~`.

I tried rstarting the Pearcleaner and it can delete those files.

**Comment by alienator88** [comment] 2024-12-06 16:07
What is that error, the same handler one from before? Sorry I can't read the language.

**Comment by L1cardo** [comment] 2024-12-06 16:10
> That unicode translates into
> 
> ```shell
> NSAppleScriptErrorBriefMessage = "处理程序不能处理这个类的对象。";
> NSAppleScriptErrorMessage = "“Finder”遇到一个错误：处理程序不能处理这个类的对象。";
> ```
> 
> Which is
> 
> ```
> NSAppleScriptErrorBriefMessage = "The handler cannot handle this type of object.";
> NSAppleScriptErrorMessage = "Finder encountered an error: The handler cannot handle this type of object.";
> ```

Yeah, the same error as this

**Comment by alienator88** [comment] 2024-12-09 17:25
I've added a check to the deletion process to do 3 things:
1. Make sure file still exists at the path before deleting
2. Check if the file is locked and if it is, try to unlock. If it fails, skip the file
3. Check that the file is writable, if it's not, skip it.

I'm hoping all these checks before actually running the uninstall command will prevent a lot of these handler issues.
Will have this out in the next release.

**Comment by alienator88** [comment] 2024-12-17 18:46
Would you be able to check if you still see Finder handler issues with the latest build?
Side note, you can now push CMD+D to open a debug console and watch the logs stream in instead of having to use Terminal.
If you do still see issues, I unfortunately will have to put a pause on trying to fix this specific issue for the time being.
 
I'm looking to move away from using AppleScript/Finder for deleting the files so this shouldn't be an issue in the future. 
I would like to move to using maybe a helper tool or some authorization services to execute sudo commands directly from Pearcleaner. Once that is done, this file handler problem shouldn't happen anymore.
For now, I'll close this issue, but feel free to reply on it as I'm curious if you still have the issue.

**Closed by alienator88** 2024-12-17 18:46 UTC

**Comment by L1cardo** [comment] 2024-12-18 17:47
After some days of use, I haven't had that issue again.

Thanks for your working on this!

**Comment by alienator88** [comment] 2024-12-18 17:51
That's good to hear and no problem at all!
It should get even more robust in the near future once I switch up how the file deletion is handled.
Thanks for reporting this!
