### ISSUE TITLE
[BUG] NIGHT THEME BUG

### ISSUE THREAD

**Issue by mightysashiman** [alienator88/Pearcleaner#113] opened 2024-09-24 17:57 UTC
**Describe the bug:** <br>
Dark them doesn't apply properly (see below in step6)

**Steps to reproduce:**
1. be during the day
2. have macos set to Settings > Appearance > Auto (light/dark)
3. set pearcleaner to settings > Interface > auto (or any light theme)
4. keep pearcleaner open
5. wait until macos switches to dark theme automatically
6. pearcleaner switch to dark them, but 2 bugs occur: app list on the right stays light themed (dark text), right pane has dark background, but text also stays black instead of turning white (thus becoming unreadable)

**Expected behavior** <br>
Pearcleaner should switch properly themes

**Info:**
 - OS: 15.0
 - Pearcleaner Version: 3.8.7

**Screenshots**
![Screenshot 2024-09-24 at 19 50 28](https://github.com/user-attachments/assets/23301a87-08ad-40ed-b59e-69d4f7ad4b07)
MacOS has already switched to night theme in this screenshot.

**Comment by alienator88** [comment] 2024-09-24 18:11
This only happens when it auto switches on schedule?
I probably never got to test that since I'd need to wait around for the OS to make the change for hours.

Because having Pearcleaner set on Auto and changing the OS appearance mode manually seems to follow the OS.
I'm not exactly sure what macOS is doing on the scheduled switch, but it "shouldn't" be any different than what the settings window allows you to choose..hmm..

**Comment by alienator88** [comment] 2024-10-15 16:22
Unfortunately I haven't been able to reproduce this myself and it's such an edge case with the timing of the scheduled switch that it could be very difficult to do.
I tried switching the appearance mode from Settings and it works fine.
I tried switching the appearance mode via applescript and it works fine.
I tried switching the appearance using the `UserDefaults AppleInterfaceStyle` variable and it works fine.

Just can't seem to reproduce this one.
I'll close this out for now since it's too much of a lift to repro for the minimal gains on this bug.

If you find a way to reproduce this manually, please let me know :)

**Closed by alienator88** 2024-10-15 16:22 UTC

**Comment by mightysashiman** [comment] 2024-10-15 16:24
yeah haven't been able to reproduce ever since either. probably a sequoia 15.0 bug that may have been fixed in 15.0.1...

**Comment by alienator88** [comment] 2024-10-15 16:26
Hopefully! 😂 
I'm so over all the Sequoia bugs man..
