### ISSUE TITLE
[BUG] ~/Library/Application Scripts/[bundle id] sometimes not displayed

### ISSUE THREAD

**Issue by tageniu** [alienator88/Pearcleaner#94] opened 2024-08-06 15:47 UTC
**Describe the bug:** <br>
The `~/Library/Application Scripts/[bundle id]` item sometimes not displayed at first, and will display after refreshing.

**Steps to reproduce:**
1. Click on an app in the list, for instance "Motrix" (Not reproducible on every app, but near half apps)
2. Notice there is no `~/Library/Application Scripts/[bundle id]` item on the right
3. Click on the app on the left again to clear the right view, then click once again
4. Notice `~/Library/Application Scripts/[bundle id]` item appears on the right

**Expected behavior** <br>
The `~/Library/Application Scripts/[bundle id]` item should appear at the first scan.

**Info:**
 - OS: 13.0.1
 - Pearcleaner Version: 3.8.4

**Additional context**
This has been a long existing problem on my two Macs running 13.0.1

**Comment by alienator88** [comment] 2024-08-06 16:05
Just tested this on Ventura 13.6 and still can't reproduce.
I don't have anything on Ventura 13..0.1 to test on.

**Comment by tageniu** [comment] 2024-08-07 04:04
Thanks for your reply. I mean this is not specific to one app (like Motrix I mentioned), but more than half of the apps on my Mac. I have attached a video below.

https://github.com/user-attachments/assets/5fb7046c-f53b-45c1-99fd-b4c2276de262

**Comment by tageniu** [comment] 2024-08-07 04:11
In addition, this is reproducible on a fresh install of macOS 13.6. See the video below:

https://github.com/user-attachments/assets/77fef4f6-8ce2-4e07-9214-b5612349e76f

**Comment by alienator88** [comment] 2024-08-07 04:16
I picked up on the issue being for more apps, I only had Motrix to test
with since that was the one mentioned.

My test was in a fresh 13.6 VM as well and I wasn’t able to see that same
issue. I’ll need to keep looking.

Do you see anything at all in the Console app if you record the log stream
while reproducing the issue?
Also, you mentioned you’ve had this problem for a while? Even on older
builds? Trying to see if it’s a bug that was introduced recently.

And last question, do you have a way to test Sonoma as well? Curious if
you’re seeing it there too on 14.0+

Thanks!

**Comment by tageniu** [comment] 2024-08-07 05:09
Hi,
I just tested on macOS 14.0 beta (23A5312d) and 15.0 beta (24A5264n), the issue appeared on the first system but not the second. The Motrix app is downloaded from [motrix.app](motrix.app) w/ bundle ID `app.motrix.native`. The Pearcleaner version I used for testing is 3.7.7 (the oldest version I can open). I tried to record console logs but found no related output.
I will try to test on more 14.x versions later.

**Comment by alienator88** [comment] 2024-08-07 15:20
Don't worry about reproducing, I was able to get it to show the bug on my end, at least on Ventura.
I still can't get it to do it on Sonoma. 
I added the app.motrix.native folder in my Application Scripts folder and on Sonoma it finds it right away.
So safe to say, this is super confusing 😂

**Comment by alienator88** [comment] 2024-08-07 15:30
Quick question, are you able to reproduce it over and over?
On the Ventura VM where I was able to see the issue, after it happened once, I can't get it to happen again. So even more confusing now..because Pearcleaner doesn't cache any found results at all. Closing the app and reopening will always be a fresh search.
So far, Sonoma and Sequoia, Motrix doesn't even create that `app.motrix.native` folder in the Application Scripts folder, so it makes sense why it's not finding it there currently. Are you doing anything in the motrix app that might be triggering it to create the folder? All I did was open the app so it generates its files and then closed it.

**Comment by alienator88** [comment] 2024-08-07 15:58
Getting closer, so found out that it's this function that triggers the creation of the folder:
https://github.com/alienator88/Pearcleaner/blob/05c491cda54b83e955d8de3bbb0c8c74a65f868a/Pearcleaner/Logic/AppPathsFetch.swift#L185

It's not necessarily something I'm doing in the app, but getting the containers for the app inadvertently triggers a macOS API to create that folder for the app..so not exactly sure how to get around that one.
I still can't reproduce it on Sonoma or Sequoia.

**Comment by tageniu** [comment] 2024-08-07 16:19
Yes, I agree it is the first searching that triggers the folder creation, and I also have no clue why this is happening. I was able to reproduce this on 14.1 (23B74) but not on 14.6 (23G80)

https://github.com/user-attachments/assets/4a25b6ae-2e16-41c7-b331-2c428eeac496

**Comment by alienator88** [comment] 2024-08-07 16:33
I narrowed it down to this call: [FileManager.default.containerURL](https://developer.apple.com/documentation/foundation/filemanager/1412643-containerurl/)
For some reason when retrieving the group container folder, macOS decides to create whatever necessary folder structure would normally be there for a Group Container in other locations, like Application Scripts. This makes no sense because all its supposed to do is return a URL.
I re-ordered the search function logic so it looks for the containers first and then searches for the app files. It should find this Application Scripts folder every time now.

Can you test this debug build for me please?
[Pearcleaner.zip](https://github.com/user-attachments/files/16531570/Pearcleaner.zip)

**Comment by tageniu** [comment] 2024-08-07 16:51
I tested on both 14.1 and 13.0.1 and it works!! Thank you very much for fixing this.

**Comment by alienator88** [comment] 2024-08-07 16:53
Awesome! I'll have this fix out in the next release. 
Thanks again for testing with me.

**Closed by alienator88** 2024-08-07 16:53 UTC
