### ISSUE TITLE
[BUG] App quit unexpectedly after uninstlalling app.

### ISSUE THREAD

**Issue by y-u-s-u-f** [alienator88/Pearcleaner#27] opened 2024-03-03 16:15 UTC
**Describe the bug**

So I had a testflight app that I just uninstalled with PearCleaner but PearCleaner just quit unexpectedly after it uninstalled it.
**To Reproduce**
1. Have a testflight app installed
2. Open Pearcleaner
3. Scroll down to the app
4. Click the uninstall button

**Expected behavior**

It stays open
**Desktop (please complete the following information):**
 - OS: 14.3.1
 - Pearcleaner App Mode: Regular
 - Pearcleaner Version: 3.0.1

**Screenshots**

![CleanShot 2024-03-03 at 08 09 33@2x](https://github.com/alienator88/Pearcleaner/assets/67281394/19d8dcac-5535-4301-8b52-9acd326bccdf)

**Additional context**

[Log.txt](https://github.com/alienator88/Pearcleaner/files/14473687/Log.txt)

**Comment by alienator88** [comment] 2024-03-03 21:20
What app was this? 
Do you have a testflight link by chance? 
I tried deleting a test flight app and didn't have any issues deleting or saw any crashes. 
Maybe it's app specific with certain file paths it might've tried to delete.

**Comment by y-u-s-u-f** [comment] 2024-03-03 23:31
https://testflight.apple.com/join/a4bmx5rA

**Comment by alienator88** [comment] 2024-03-04 17:32
I tested this out and I'm not able to reproduce the problem at all, with this Untitled Podcast app or any other testflight app.
Are you able to reproduce the issue every single time? Or was it a one time thing?

**Comment by y-u-s-u-f** [comment] 2024-03-04 18:03
I am able to reproduce it every time.

**Comment by alienator88** [comment] 2024-03-04 18:37
Can you try something for me?
Open Console.app and make sure menu bar Action > Include Debug Messages is enabled.
Then in the search field, set it to `com.alienator88.Pearcleaner` and the type to subprocess:
![image](https://github.com/alienator88/Pearcleaner/assets/6263626/aa2fc016-99d7-4a50-8a03-94a606e88a7a)

Start recording and reproduce the issue and let me know if you catch any debug errors in there.

**Comment by y-u-s-u-f** [comment] 2024-03-08 04:14
Hey!

I'm actually no longer experience the crash issue. However, now I encounter a new error when uninstalling the app. You can check out the attached image for more details.

Yusuf.

Sent via Superhuman ( ***@***.*** )

**Comment by alienator88** [comment] 2024-03-08 06:51
Sorry, I don’t see an attached image.

**Comment by alienator88** [comment] 2024-03-14 22:07
Closing for now, update the issue if you still have problems.

**Closed by alienator88** 2024-03-14 22:07 UTC
